### ISSUE TITLE
Uncaught TypeError: Cannot read property 'saveSubscription' of undefined

### ISSUE THREAD

**Issue by arsari** [nmscholl/nms-color-bracket#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [nms-color-bracket](https://github.com/nmscholl/nms-color-bracket) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'saveSubscription' of undefined

```
At /Users/arsari/.atom/packages/nms-color-bracket/lib/nms-color-bracket.js:54

TypeError: Cannot read property 'saveSubscription' of undefined
    at Object.process_current_page (/packages/nms-color-bracket/lib/nms-color-bracket.js:54:14)
    at Object.toggle (/packages/nms-color-bracket/lib/nms-color-bracket.js:34:14)
    at /packages/nms-color-bracket/lib/nms-color-bracket.js:14:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:49.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-one-dark-syntax.theme-atom-material-ui)
     -0:07.2.0 nms-color-bracket:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
animated-cursor 1.1.0 
atom-beautify 0.29.18 
atom-clock 0.1.6 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-monokai 0.10.9 
atom-shortcuts 0.0.2 
autoclose-html 0.23.0 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
autocomplete-python 1.8.63 
autoprefixer 3.6.1 
browser-plus 0.0.87 
busy-signal 1.3.0 
cobalt2-syntax 0.5.1 
color-picker 2.2.5 
compare-files 0.8.0 
cssnano 1.1.0 
emmet 2.4.3 
file-icons 2.1.3 
git-plus 7.4.0 
glowing-cursor 0.1.2 
highlight-column 0.5.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-babel 2.57.3 
linter 2.1.2 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-pycodestyle 2.0.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
linter-write-good 0.9.0 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
nms-color-bracket 0.1.0 
open-in-browsers 0.0.19 
open-terminal-here 2.3.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
qolor 0.4.1 
uglify 1.3.1 
```

**Comment by RogerAntonio** [comment]
Nice, atom redirects me to this page but it hasn't been looked at in a year.
I just installed this package..

**Comment by ghost** [comment]
Just found the replacement:
https://atom.io/packages/bracket-colorizer

**Comment by linjialiang** [comment]
I have the same problem

**Comment by linjialiang** [comment]
`bracket-colorizer` Unable to flash @tgrushka
